/* deploy refresh */
(function(){
const STYLE=`
.fpa-nav-btn{position:absolute;top:calc(14px + env(safe-area-inset-top));right:14px;z-index:80;width:50px;height:50px;border:1px solid #ffffff55;border-radius:16px;background:#ffffffee;color:#102033;box-shadow:0 8px 24px #10203324;font-size:0;font-weight:900;cursor:pointer;display:grid;place-items:center;backdrop-filter:blur(10px);-webkit-backdrop-filter:blur(10px)}.fpa-nav-btn:before{content:"";width:22px;height:16px;background:linear-gradient(#102033 0 0) 0 0/100% 2px no-repeat,linear-gradient(#102033 0 0) 0 7px/72% 2px no-repeat,linear-gradient(#102033 0 0) 0 14px/100% 2px no-repeat}.fpa-nav-btn:active{transform:scale(.96)}
.fpa-app-head{display:flex;align-items:center;gap:11px;min-height:78px;padding:12px 78px 12px 18px;background:linear-gradient(135deg,var(--fpa-primary,#1357A6),color-mix(in srgb,var(--fpa-primary,#1357A6) 82%,#07111f));color:var(--fpa-header-text,#fff);border-bottom:4px solid var(--fpa-secondary,#fff);box-shadow:0 5px 18px #10203320}.fpa-app-head-badge{width:48px;height:48px;flex:0 0 48px;border-radius:15px;overflow:hidden;background:#fff;display:grid;place-items:center;font-weight:900;color:#1357A6;box-shadow:0 3px 10px #0002}.fpa-app-head-badge img{width:100%;height:100%;object-fit:contain;padding:4px}.fpa-app-head-club{font-size:18px;font-weight:900;line-height:1.05;letter-spacing:-.01em}.fpa-app-head-team{font-size:12px;color:inherit;opacity:.8;margin-top:4px;font-weight:700}.fpa-brand-foot{display:flex;align-items:center;justify-content:center;gap:8px;padding:22px 12px calc(22px + env(safe-area-inset-bottom));color:#102033;font-weight:900;letter-spacing:.08em;font-size:12px}.fpa-brand-foot img{width:28px;height:28px;object-fit:contain}
.fpa-nav-shade{position:fixed;inset:0;background:#07111f99;z-index:81;opacity:0;pointer-events:none;transition:opacity .22s ease;backdrop-filter:blur(3px);-webkit-backdrop-filter:blur(3px)}.fpa-nav-shade.open{opacity:1;pointer-events:auto}
.fpa-nav{position:fixed;top:8px;bottom:8px;left:8px;width:min(74vw,276px);background:#f7f9fb;z-index:82;transform:translateX(calc(-100% - 18px));transition:transform .24s cubic-bezier(.2,.8,.2,1);box-shadow:20px 0 60px #07111f4a;border:1px solid #ffffff88;border-radius:24px;padding:0;display:flex;flex-direction:column;overflow:hidden;color:#102033;font-family:Arial,Helvetica,sans-serif}.fpa-nav.open{transform:translateX(0)}
.fpa-nav-head{display:flex;align-items:center;justify-content:space-between;padding:calc(18px + env(safe-area-inset-top)) 16px 18px;background:linear-gradient(145deg,var(--fpa-primary,#1357A6),color-mix(in srgb,var(--fpa-primary,#1357A6) 76%,#07111f));color:var(--fpa-header-text,#fff);position:relative;overflow:hidden}.fpa-nav-head:after{content:"";position:absolute;width:150px;height:150px;border-radius:50%;right:-65px;top:-70px;background:#ffffff12}.fpa-nav-team{display:flex;align-items:center;gap:11px;min-width:0;position:relative;z-index:1}.fpa-nav-badge{width:48px;height:48px;flex:0 0 48px;border-radius:14px;overflow:hidden;background:#fff;display:grid;place-items:center;font-weight:900;color:#1357A6;box-shadow:0 4px 12px #0002}.fpa-nav-badge img{width:100%;height:100%;object-fit:contain;padding:4px}.fpa-nav-title{display:block;font-size:15px;font-weight:900;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:150px}.fpa-nav-club{display:block;color:inherit;opacity:.72;font-size:11px;margin-top:3px}.fpa-nav-close{position:relative;z-index:2;border:1px solid #ffffff36;background:#ffffff18;color:inherit;width:38px;height:38px;border-radius:12px;font-size:24px;line-height:1;cursor:pointer;display:grid;place-items:center}.fpa-nav-close:active{background:#ffffff2a}
.fpa-nav-section{padding:14px 14px 5px;color:#8190a0;font-size:9px;font-weight:900;letter-spacing:.14em;text-transform:uppercase}.fpa-nav-links{display:grid;gap:4px;padding:8px 10px 12px;overflow:auto}.fpa-nav-links a{position:relative;border-radius:14px;padding:9px 10px;display:flex;align-items:center;gap:11px;text-decoration:none;text-align:left;font-size:15px;font-weight:850;color:#1b2b3a;min-height:48px;transition:background .15s,color .15s,transform .15s}.fpa-nav-links a:active{transform:scale(.985)}.fpa-nav-links a:hover{background:#eef3f7}.fpa-nav-links a.active{background:#fff;color:var(--fpa-primary,#1357A6);box-shadow:0 4px 14px #10203310}.fpa-nav-links a.active:before{content:"";position:absolute;left:0;top:10px;bottom:10px;width:4px;border-radius:4px;background:var(--fpa-primary,#1357A6)}.fpa-nav-ico{width:34px;height:34px;flex:0 0 34px;border-radius:10px;background:#eaf0f5;display:grid;place-items:center;color:#526273}.fpa-nav-links a.active .fpa-nav-ico{background:color-mix(in srgb,var(--fpa-primary,#1357A6) 12%,#fff);color:var(--fpa-primary,#1357A6)}.fpa-nav-ico svg{width:18px;height:18px;display:block;fill:none;stroke:currentColor;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}
.fpa-nav-foot{margin-top:auto;border-top:1px solid #e1e8ee;padding:10px}.fpa-nav-foot button{width:100%;border:0;background:transparent;border-radius:13px;padding:11px 12px;text-align:left;font-weight:800;cursor:pointer;color:#657483;display:flex;align-items:center;gap:9px}.fpa-nav-foot button:active{background:#eef3f7}.fpa-nav-foot button:before{content:"↪";width:28px;height:28px;border-radius:9px;background:#eaf0f5;display:grid;place-items:center;color:#526273}
@media(max-width:420px){.fpa-nav{top:6px;bottom:6px;left:6px;width:min(80vw,270px);border-radius:22px}.fpa-nav-head{padding-left:14px;padding-right:12px}.fpa-nav-links{padding-left:8px;padding-right:8px}}
`;
async function mount(opts={}){
 if(document.getElementById('fpaSharedNav'))return;
 const q=new URLSearchParams(location.search),tid=opts.teamId||q.get('team')||q.get('id');if(!tid)return;
 if(!document.getElementById('fpaSharedNavStyle')){const s=document.createElement('style');s.id='fpaSharedNavStyle';s.textContent=STYLE;document.head.appendChild(s)}
 let features={},team={},club={},canManage=false;
 try{let r=await sb.from('team_features').select('*').eq('team_id',tid).maybeSingle();features=r.data||{};r=await sb.from('teams').select('id,name,club_id,badge_url').eq('id',tid).maybeSingle();team=r.data||{};if(team.club_id){r=await sb.from('clubs').select('name,primary_colour,secondary_colour').eq('id',team.club_id).maybeSingle();club=r.data||{}}const {data:{session}}=await sb.auth.getSession();if(session){const [tm,cm,pa]=await Promise.all([sb.from('team_memberships').select('role').eq('team_id',tid).eq('user_id',session.user.id).eq('active',true).maybeSingle(),team.club_id?sb.from('club_memberships').select('role').eq('club_id',team.club_id).eq('user_id',session.user.id).eq('active',true).maybeSingle():Promise.resolve({data:null}),sb.from('platform_admins').select('user_id').eq('user_id',session.user.id).eq('active',true).maybeSingle()]);canManage=!!pa.data||['team_admin','manager','coach'].includes(tm.data?.role)||['owner','club_admin'].includes(cm.data?.role)}}catch(e){}
 const primary=club.primary_colour||'#1357A6',secondary=club.secondary_colour||'#FFFFFF';const applyColours=()=>{const h=String(primary).replace('#',''),r=parseInt(h.slice(0,2),16)||0,g=parseInt(h.slice(2,4),16)||0,b=parseInt(h.slice(4,6),16)||0,y=(r*299+g*587+b*114)/1000,root=document.documentElement;root.style.setProperty('--blue',primary);root.style.setProperty('--fpa-primary',primary);root.style.setProperty('--fpa-secondary',secondary);root.style.setProperty('--fpa-accent',primary);root.style.setProperty('--fpa-header-text',y>165?'#102033':'#FFFFFF')};applyColours();
 const preview=q.get('dev_preview')==='1'?'&dev_preview=1':'';
 const icon=k=>({home:'<svg viewBox="0 0 24 24"><path d="M3 11.5 12 4l9 7.5"></path><path d="M5.5 10.5V20h13v-9.5"></path><path d="M9.5 20v-6h5v6"></path></svg>',dashboard:'<svg viewBox="0 0 24 24"><path d="M4 19V9"></path><path d="M10 19V5"></path><path d="M16 19v-7"></path><path d="M22 19H2"></path></svg>',fixtures:'<svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="16" rx="2"></rect><path d="M8 3v4M16 3v4M3 10h18"></path></svg>',match:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"></circle><path d="m12 8 3 2-1 4h-4l-1-4 3-2Z"></path><path d="m9 10-4-1M15 10l4-1M10 14l-2 4M14 14l2 4"></path></svg>',players:'<svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"></circle><path d="M3.5 19c.5-4 2.5-6 5.5-6s5 2 5.5 6"></path><circle cx="17" cy="9" r="2.5"></circle><path d="M15 14c3.5-.3 5.2 1.4 5.5 5"></path></svg>',training:'<svg viewBox="0 0 24 24"><rect x="5" y="4" width="14" height="17" rx="2"></rect><path d="M9 4.5V3h6v1.5"></path><path d="m8.5 12 2 2 4.5-5"></path></svg>',voting:'<svg viewBox="0 0 24 24"><path d="M7 4h10l2 5H5l2-5Z"></path><rect x="4" y="9" width="16" height="11" rx="2"></rect><path d="m9 14 2 2 4-4"></path></svg>',subs:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"></circle><path d="M15 8.5c-.7-.7-1.5-1-2.7-1-1.7 0-2.8.8-2.8 2 0 3 6 1.5 6 4.5 0 1.3-1.2 2.2-3 2.2-1.3 0-2.4-.4-3.2-1.2M12 5.5v13"></path></svg>',settings:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"></circle><path d="M19 13.5v-3l-2-.7-.7-1.7.9-1.9-2.1-2.1-1.9.9-1.7-.7L10.5 2h-3l-.7 2-1.7.7-1.9-.9L1.1 6l.9 1.9-.7 1.7-2 .7v3l2 .7.7 1.7-.9 1.9 2.1 2.1 1.9-.9 1.7.7.7 2h3l.7-2 1.7-.7 1.9.9 2.1-2.1-.9-1.9.7-1.7 2-.7Z" transform="translate(2 0) scale(.83)"></path></svg>'}[k]||'');
 const teamItems=[
  ['home','Home','/index.html?team='+tid+preview,null,true],
  ['fixtures','Fixtures','/fixtures.html?team='+tid+preview,null,true],
  ['match','Match Centre','/match-centre.html?team='+tid+preview,'match_centre',true],
  ['dashboard','Dashboard','/dashboard.html?team='+tid+preview,null,true],
  ['players','Players & Training','/players.html?team='+tid+preview,'players',true],
  ['voting','Voting','/voting.html?team='+tid+preview,'voting',true],
  ['subs','Subs Admin','/subs.html?team='+tid+preview,'subs_finance',canManage],
  ['settings','Settings','/team-settings.html?team='+tid+preview,null,canManage]
 ].filter(x=>(!x[3]||features[x[3]]!==false)&&x[4]);
 const shade=document.createElement('div');shade.className='fpa-nav-shade';shade.id='fpaSharedNavShade';
 const nav=document.createElement('aside');nav.className='fpa-nav';nav.id='fpaSharedNav';
 const badge=team.badge_url?'<img src="'+team.badge_url+'" alt="">':'FP';
 const here=location.pathname.replace(/\/$/,'')||'/index.html';
 const renderItems=items=>items.map(x=>{const path=x[2].split('?')[0],active=(here===path||(here==='/'&&path==='/index.html'))?' active':'';return '<a class="'+active.trim()+'" href="'+x[2]+'"><span class="fpa-nav-ico">'+icon(x[0])+'</span><span>'+x[1]+'</span></a>'}).join('');
 nav.innerHTML='<div class="fpa-nav-head"><div class="fpa-nav-team"><div class="fpa-nav-badge">'+badge+'</div><div style="min-width:0"><span class="fpa-nav-title">'+(team.name||'Football PA')+'</span><span class="fpa-nav-club">'+(club.name||'')+'</span></div></div><button class="fpa-nav-close" aria-label="Close menu">×</button></div><div class="fpa-nav-section">Team</div><nav class="fpa-nav-links">'+renderItems(teamItems)+'</nav><div class="fpa-nav-foot"><button id="fpaNavSignOut">Sign out</button></div>';
 const btn=document.createElement('button');btn.className='fpa-nav-btn';btn.id='fpaSharedNavBtn';btn.setAttribute('aria-label','Open menu');btn.textContent='☰';
 const oldHeaders=document.querySelectorAll('.top,.topbar,.fpa-pagebar');oldHeaders.forEach(h=>h.style.display='none');const head=document.createElement('header');head.className='fpa-app-head';head.id='fpaAppHead';head.innerHTML='<div class="fpa-app-head-badge">'+badge+'</div><div><div class="fpa-app-head-club">'+(club.name||'Football PA')+'</div><div class="fpa-app-head-team">'+(team.name||'')+'</div></div>';const foot=document.createElement('footer');foot.className='fpa-brand-foot';foot.innerHTML='<img src="https://raw.githubusercontent.com/PerranporthAFCMens/Football-PA/main/football-pa-logo-dark.svg" alt=""><span>FOOTBALL PA</span>';document.body.prepend(head);document.body.append(shade,nav,btn,foot);
 const close=()=>{shade.classList.remove('open');nav.classList.remove('open')};btn.onclick=()=>{shade.classList.add('open');nav.classList.add('open')};shade.onclick=close;nav.querySelector('.fpa-nav-close').onclick=close;nav.querySelector('#fpaNavSignOut').onclick=async()=>{await sb.auth.signOut();location.href='/login.html'};
 }
 window.FootballPANav={mount};
})();