(function(){
const STYLE=`
.fpa-nav-btn{position:absolute;top:calc(14px + env(safe-area-inset-top));right:14px;z-index:80;width:48px;height:48px;border:1px solid #cbd6e2;border-radius:15px;background:#fff;color:#102033;box-shadow:0 5px 16px #10203320;font-size:25px;font-weight:900;cursor:pointer}.fpa-app-head{display:flex;align-items:center;gap:10px;min-height:76px;padding:12px 74px 12px 18px;background:var(--fpa-primary,#1357A6);color:var(--fpa-header-text,#fff);border-bottom:5px solid var(--fpa-secondary,#fff);box-shadow:0 4px 14px #10203318}.fpa-app-head-badge{width:46px;height:46px;flex:0 0 46px;border-radius:50%;overflow:hidden;background:#fff;display:grid;place-items:center;font-weight:900;color:#1357A6}.fpa-app-head-badge img{width:100%;height:100%;object-fit:contain;padding:3px}.fpa-app-head-club{font-size:18px;font-weight:900;line-height:1.05}.fpa-app-head-team{font-size:13px;color:inherit;opacity:.78;margin-top:4px}.fpa-brand-foot{display:flex;align-items:center;justify-content:center;gap:8px;padding:22px 12px calc(22px + env(safe-area-inset-bottom));color:#102033;font-weight:900;letter-spacing:.08em;font-size:12px}.fpa-brand-foot img{width:28px;height:28px;object-fit:contain}
.fpa-nav-shade{position:fixed;inset:0;background:#0b172666;z-index:81;opacity:0;pointer-events:none;transition:opacity .2s}.fpa-nav-shade.open{opacity:1;pointer-events:auto}
.fpa-nav{position:fixed;inset:0 auto 0 0;width:min(72vw,270px);background:#fff;z-index:82;transform:translateX(-102%);transition:transform .22s ease;box-shadow:18px 0 45px #1020332b;padding:calc(10px + env(safe-area-inset-top)) 10px calc(10px + env(safe-area-inset-bottom));display:flex;flex-direction:column;color:#102033;font-family:Arial,Helvetica,sans-serif}.fpa-nav.open{transform:translateX(0)}
.fpa-nav-head{display:flex;align-items:center;justify-content:space-between;padding:2px 3px 10px;border-bottom:1px solid #d9e3ec}.fpa-nav-team{display:flex;align-items:center;gap:10px;min-width:0}.fpa-nav-badge{width:34px;height:34px;flex:0 0 34px;border-radius:50%;overflow:hidden;background:#eef3f8;display:grid;place-items:center;font-weight:900;color:#1357A6}.fpa-nav-badge img{width:100%;height:100%;object-fit:contain;padding:3px}.fpa-nav-title{display:block;font-size:14px;font-weight:900;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.fpa-nav-club{display:block;color:#6d7b8a;font-size:11px}.fpa-nav-close{border:0;background:transparent;color:#1762ae;font-size:27px;padding:7px;cursor:pointer}
.fpa-nav-links{display:grid;gap:1px;padding:6px 0}.fpa-nav-links a{border-radius:10px;padding:9px 10px;display:flex;align-items:center;gap:10px;text-decoration:none;text-align:left;font-size:17px;font-weight:900;color:#102033}.fpa-nav-links a:active,.fpa-nav-links a.active{background:#eef4fb;color:#1357A6}.fpa-nav-ico{width:22px;text-align:center;font-size:18px}.fpa-nav-foot{margin-top:auto;border-top:1px solid #d9e3ec;padding-top:10px}.fpa-nav-foot button{width:100%;border:0;background:transparent;border-radius:10px;padding:12px;text-align:left;font-weight:800;cursor:pointer;color:#102033}
`;
async function mount(opts={}){
 if(document.getElementById('fpaSharedNav'))return;
 const q=new URLSearchParams(location.search),tid=opts.teamId||q.get('team')||q.get('id');if(!tid)return;
 if(!document.getElementById('fpaSharedNavStyle')){const s=document.createElement('style');s.id='fpaSharedNavStyle';s.textContent=STYLE;document.head.appendChild(s)}
 let features={},team={},club={},canManage=false;
 try{let r=await sb.from('team_features').select('*').eq('team_id',tid).maybeSingle();features=r.data||{};r=await sb.from('teams').select('id,name,club_id,badge_url').eq('id',tid).maybeSingle();team=r.data||{};if(team.club_id){r=await sb.from('clubs').select('name,primary_colour,secondary_colour').eq('id',team.club_id).maybeSingle();club=r.data||{}}const {data:{session}}=await sb.auth.getSession();if(session){const [tm,cm,pa]=await Promise.all([sb.from('team_memberships').select('role').eq('team_id',tid).eq('user_id',session.user.id).eq('active',true).maybeSingle(),team.club_id?sb.from('club_memberships').select('role').eq('club_id',team.club_id).eq('user_id',session.user.id).eq('active',true).maybeSingle():Promise.resolve({data:null}),sb.from('platform_admins').select('user_id').eq('user_id',session.user.id).eq('active',true).maybeSingle()]);canManage=!!pa.data||['team_admin','manager','coach'].includes(tm.data?.role)||['owner','club_admin'].includes(cm.data?.role)}}catch(e){}
 const primary=club.primary_colour||'#1357A6',secondary=club.secondary_colour||'#FFFFFF';const applyColours=()=>{const h=String(primary).replace('#',''),r=parseInt(h.slice(0,2),16)||0,g=parseInt(h.slice(2,4),16)||0,b=parseInt(h.slice(4,6),16)||0,y=(r*299+g*587+b*114)/1000,root=document.documentElement;root.style.setProperty('--blue',primary);root.style.setProperty('--fpa-primary',primary);root.style.setProperty('--fpa-secondary',secondary);root.style.setProperty('--fpa-accent',primary);root.style.setProperty('--fpa-header-text',y>165?'#102033':'#FFFFFF')};applyColours();
 const preview=q.get('dev_preview')==='1'?'&dev_preview=1':'';
 const items=[['⌂','Home','/index.html?team='+tid+preview,null,true],['📅','Fixtures','/fixtures.html?team='+tid+preview,null,true],['⚽','Match Centre','/match-centre.html?team='+tid+preview,'match_centre',true],['👥','Players','/players.html?team='+tid+preview,'players',true],['🗳️','Voting','/voting.html?team='+tid+preview,'voting',true],['💷','Subs Admin','/subs.html?team='+tid+preview,'subs_finance',canManage],['⚙️','Settings','/team-settings.html?team='+tid+preview,null,canManage]].filter(x=>(!x[3]||features[x[3]]!==false)&&x[4]);
 const shade=document.createElement('div');shade.className='fpa-nav-shade';shade.id='fpaSharedNavShade';
 const nav=document.createElement('aside');nav.className='fpa-nav';nav.id='fpaSharedNav';
 const badge=team.badge_url?'<img src="'+team.badge_url+'" alt="">':'FP';
 nav.innerHTML='<div class="fpa-nav-head"><div class="fpa-nav-team"><div class="fpa-nav-badge">'+badge+'</div><div style="min-width:0"><span class="fpa-nav-title">'+(team.name||'Football PA')+'</span><span class="fpa-nav-club">'+(club.name||'')+'</span></div></div><button class="fpa-nav-close" aria-label="Close menu">×</button></div><nav class="fpa-nav-links">'+items.map(x=>'<a href="'+x[2]+'"><span class="fpa-nav-ico">'+x[0]+'</span>'+x[1]+'</a>').join('')+'</nav><div class="fpa-nav-foot"><button id="fpaNavSignOut">↪ Sign out</button></div>';
 const btn=document.createElement('button');btn.className='fpa-nav-btn';btn.id='fpaSharedNavBtn';btn.setAttribute('aria-label','Open menu');btn.textContent='☰';
 const oldHeaders=document.querySelectorAll('.top,.topbar,.fpa-pagebar');oldHeaders.forEach(h=>h.style.display='none');const head=document.createElement('header');head.className='fpa-app-head';head.id='fpaAppHead';head.innerHTML='<div class="fpa-app-head-badge">'+badge+'</div><div><div class="fpa-app-head-club">'+(club.name||'Football PA')+'</div><div class="fpa-app-head-team">'+(team.name||'')+'</div></div>';const foot=document.createElement('footer');foot.className='fpa-brand-foot';foot.innerHTML='<img src="https://raw.githubusercontent.com/PerranporthAFCMens/Football-PA/main/football-pa-logo-dark.svg" alt=""><span>FOOTBALL PA</span>';document.body.prepend(head);document.body.append(shade,nav,btn,foot);
 const close=()=>{shade.classList.remove('open');nav.classList.remove('open')};btn.onclick=()=>{shade.classList.add('open');nav.classList.add('open')};shade.onclick=close;nav.querySelector('.fpa-nav-close').onclick=close;nav.querySelector('#fpaNavSignOut').onclick=async()=>{await sb.auth.signOut();location.href='/login.html'};
 }
 window.FootballPANav={mount};
})();