import fs from 'node:fs';
const pages=['index.html','dashboard.html','players.html','match-centre.html','team-settings.html','fixture-sync.html','fixtures.html','voting.html','subs.html','player-portal.html'];
let failed=false;const fail=(file,msg)=>{failed=true;console.error(`FAIL ${file}: ${msg}`)};
for(const file of pages){const html=fs.readFileSync(file,'utf8');const ids=[...html.matchAll(/\bid=["']([^"']+)["']/g)].map(m=>m[1]);const seen=new Set();for(const id of ids){if(seen.has(id))fail(file,`duplicate id "${id}"`);seen.add(id)}const refs=[...html.matchAll(/\$('([^']+)'\)/g)].map(m=>m[1]);for(const id of new Set(refs)){if(!seen.has(id))fail(file,`JavaScript references missing element #${id}`)}for(const m of html.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi)){try{new Function(m[1])}catch(e){fail(file,`inline JavaScript syntax error: ${e.message}`)}}if(!html.includes('/core-ui.css'))fail(file,'missing shared /core-ui.css');if(!html.includes('/core-nav.js'))fail(file,'missing shared /core-nav.js');const visible=html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ');for(const phrase of ['Saved to Supabase','Synced from Supabase','Core test','browser-only','secure Dev access'])if(visible.toLowerCase().includes(phrase.toLowerCase()))fail(file,`customer-facing debug wording: "${phrase}"`);if(/Club_Logo\.png/i.test(html))fail(file,'hardcoded club logo found');if((html.match(/FootballPANav\.mount/g)||[]).length>1)fail(file,'shared navigation mounted more than once')}
const nav=fs.readFileSync('core-nav.js','utf8');try{new Function(nav)}catch(e){fail('core-nav.js',`syntax error: ${e.message}`)}if(/deploy refresh/i.test(nav))fail('core-nav.js','temporary deployment marker still present');const navOrder=["'Home'","'Match Centre'","'Players'","'Fixtures'","'Dashboard'","'Live Score'","'Settings'"].map(x=>nav.indexOf(x));if(navOrder.some(x=>x<0)||navOrder.some((x,i)=>i&&x<=navOrder[i-1]))fail('core-nav.js','main navigation order is incorrect');if(/\['voting','Voting'|\['subs','Subs Admin'/.test(nav))fail('core-nav.js','Voting or Subs Admin still present in main navigation');
const match=fs.readFileSync('match-centre.html','utf8');if(/45\s*\*\s*60|90\s*\*\s*60/.test(match))fail('match-centre.html','hardcoded 45/90 minute match timing found');if(/\.from\(['"]players['"]\)[\s\S]{0,250}\.eq\(['"]club_id['"]/.test(match))fail('match-centre.html','loads club-wide players instead of team_players');if(/['"]in_progress['"]/.test(match))fail('match-centre.html','uses invalid fixture status in_progress');if(/team_side[^\n]{0,80}['"]ours['"]/.test(match))fail('match-centre.html','uses legacy team_side "ours" instead of "us"');if(!match.includes("Six-yard box")||!match.includes("Central box"))fail('match-centre.html','approved goal-zone map is missing');if(!match.includes("set_match_starting_lineup"))fail('match-centre.html','starting lineup is not saved through the dedicated history RPC');if(!match.includes("starting_xi"))fail('match-centre.html','starting lineup confirmation state is not loaded separately from current XI');if(!match.includes("substitutionFromDb"))fail('match-centre.html','saved substitutions are not rebuilt into the event feed');
const playerHtml=fs.readFileSync('players.html','utf8');if(/Player Dashboard|dash-switch/.test(playerHtml))fail('players.html','stale player-dashboard UI remains');if((playerHtml.match(/FootballPANav\.mount/g)||[]).length!==1)fail('players.html','shared navigation should mount exactly once');
const redirect=fs.readFileSync('training.html','utf8');if(!redirect.includes('/players.html'))fail('training.html','legacy training route does not redirect');
const live=fs.readFileSync('live-score.html','utf8');if(!live.includes('team-scoreboard'))fail('live-score.html','public scoreboard endpoint missing');if(!live.includes('shareBtn'))fail('live-score.html','share control missing');
if(!playerHtml.includes('Save & lock session'))fail('players.html','training session lock control missing');
if(!playerHtml.includes('Surname A–Z'))fail('players.html','player surname sort control missing');
const sync=fs.readFileSync('fixture-sync.html','utf8');if(!sync.includes('fixtureDateHasPassed'))fail('fixture-sync.html','past missing fixtures are not protected');if(!sync.includes('fixture_sync_ignored_updates')||!sync.includes('ignoreChange'))fail('fixture-sync.html','ignored fixture updates are not persisted');
const home=fs.readFileSync('index.html','utf8');if(!home.includes('Coming up'))fail('index.html','Coming up Home card missing');if(/More tools|ACTIVE PLAYERS|Voting|Subs Admin/.test(home))fail('index.html','unsupported or old Home card content remains');if(!home.includes('data-upcoming'))fail('index.html','Coming up fixtures are not rendered');if(!home.includes('fixture_sync_ignored_updates'))fail('index.html','Home fixture notice does not respect ignored updates');
if(failed)process.exit(1);console.log('Football PA Core smoke checks passed.');