import fs from 'node:fs';
const pages=['index.html','dashboard.html','players.html','match-centre.html','team-settings.html','fixture-sync.html','fixtures.html','voting.html','subs.html','player-portal.html'];
let failed=false;const fail=(file,msg)=>{failed=true;console.error(`FAIL ${file}: ${msg}`)};
for(const file of pages){const html=fs.readFileSync(file,'utf8');const ids=[...html.matchAll(/\bid=["']([^"']+)["']/g)].map(m=>m[1]);const seen=new Set();for(const id of ids){if(seen.has(id))fail(file,`duplicate id "${id}"`);seen.add(id)}const refs=[...html.matchAll(/\$('([^']+)'\)/g)].map(m=>m[1]);for(const id of new Set(refs)){if(!seen.has(id))fail(file,`JavaScript references missing element #${id}`)}for(const m of html.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi)){try{new Function(m[1])}catch(e){fail(file,`inline JavaScript syntax error: ${e.message}`)}}if(!html.includes('/core-ui.css'))fail(file,'missing shared /core-ui.css');if(!html.includes('/core-nav.js'))fail(file,'missing shared /core-nav.js');const visible=html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ');for(const phrase of ['Saved to Supabase','Synced from Supabase','Core test','browser-only','secure Dev access'])if(visible.toLowerCase().includes(phrase.toLowerCase()))fail(file,`customer-facing debug wording: "${phrase}"`);if(/Club_Logo\.png/i.test(html))fail(file,'hardcoded club logo found');if((html.match(/FootballPANav\.mount/g)||[]).length>1)fail(file,'shared navigation mounted more than once')}
const nav=fs.readFileSync('core-nav.js','utf8');try{new Function(nav)}catch(e){fail('core-nav.js',`syntax error: ${e.message}`)}if(/deploy refresh/i.test(nav))fail('core-nav.js','temporary deployment marker still present');
const match=fs.readFileSync('match-centre.html','utf8');if(/45\s*\*\s*60|90\s*\*\s*60/.test(match))fail('match-centre.html','hardcoded 45/90 minute match timing found');if(/\.from\(['"]players['"]\)[\s\S]{0,250}\.eq\(['"]club_id['"]/.test(match))fail('match-centre.html','loads club-wide players instead of team_players');if(/['"]in_progress['"]/.test(match))fail('match-centre.html','uses invalid fixture status in_progress');if(/team_side[^\n]{0,80}['"]ours['"]/.test(match))fail('match-centre.html','uses legacy team_side "ours" instead of "us"');if(!match.includes("Six-yard box")||!match.includes("Central box"))fail('match-centre.html','approved goal-zone map is missing');
const playerHtml=fs.readFileSync('players.html','utf8');if(/Player Dashboard|dash-switch/.test(playerHtml))fail('players.html','stale player-dashboard UI remains');if((playerHtml.match(/FootballPANav\.mount/g)||[]).length!==1)fail('players.html','shared navigation should mount exactly once');
const redirect=fs.readFileSync('training.html','utf8');if(!redirect.includes('/players.html'))fail('training.html','legacy training route does not redirect');
const live=fs.readFileSync('live-score.html','utf8');if(!live.includes('team-scoreboard'))fail('live-score.html','public scoreboard endpoint missing');if(!live.includes('shareBtn'))fail('live-score.html','share control missing');
if(!playerHtml.includes('Save & lock session'))fail('players.html','training session lock control missing');
if(!playerHtml.includes('Surname A–Z'))fail('players.html','player surname sort control missing');
if(failed)process.exit(1);console.log('Football PA Core smoke checks passed.');